### ISSUE TITLE
執行錯誤

### ISSUE THREAD

**Issue by wibe01204** [KT-Yeh/Genshin-Discord-Bot#15]
問題如下
```

              原神小幫手              System : Windows
 Python v3.9.13   discord.py v2.1.0a4618+gba2ad580   genshin.py v1.2.4   LogTool v3.1

2022-11-01 21:47:55 WARNING  discord.ext.commands.bot Privileged message content intent is missing, commands may not work as expected.
Privileged message content intent is missing, commands may not work as expected.
2022-11-01 21:47:55 INFO     discord.client logging in using static token
logging in using static token
[11-01 21:47:56]【系統】on_close: 資料庫已關閉
[11-01 21:47:56]【系統】on_close: 機器人已結束
Traceback (most recent call last):
  File "C:\Users\Yu-Home\Desktop\Genshin-Discord-Bot-master\main.py", line 69, in <module>
    client.run(config.bot_token)
  File "C:\Users\Yu-Home\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 828, in run
    asyncio.run(runner())
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Yu-Home\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 817, in runner
    await self.start(token, reconnect=reconnect)
  File "C:\Users\Yu-Home\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 745, in start
    await self.login(token)
  File "C:\Users\Yu-Home\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 589, in login
    await self.setup_hook()
  File "C:\Users\Yu-Home\Desktop\Genshin-Discord-Bot-master\main.py", line 32, in setup_hook
    await genshin.utility.update_characters_ambr(['zh-tw'])
AttributeError: module 'genshin.utility' has no attribute 'update_characters_ambr'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000027910CF4820>
Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python39\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed```

**Comment by KT-Yeh** [comment]
更新 genshin.py

**Comment by wibe01204** [comment]
@KT-Yeh 可以了 小弟在雷
感謝~~
