### ISSUE TITLE
Error while i run 

### ISSUE THREAD

**Issue by fakesmile0** [KT-Yeh/Genshin-Discord-Bot#22]
Traceback (most recent call last):
  File "/root/discordstuff/Genshin-Discord-Bot/main.py", line 8, in <module>
    from utility.CustomLog import LOG
  File "/root/discordstuff/Genshin-Discord-Bot/utility/CustomLog.py", line 463, in <module>
    LOG = LogTool()
  File "/root/discordstuff/Genshin-Discord-Bot/utility/CustomLog.py", line 211, in __init__
    print(f"\n              {self._MIKU_GREEN}\u539f\u795e\u5c0f\u5e6b\u624b{self.RESET}              System : {self._LIGHT_CYAN}{platform.system()}\n"
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 33-37: ordinal not in range(256)

**Comment by GauravM512** [comment]
which terminal?

**Comment by fakesmile0** [comment]
> which terminal?

root@kvm5074:~/discordstuff/Genshin-Discord-Bot# python3 main.py
Traceback (most recent call last):
  File "/root/discordstuff/Genshin-Discord-Bot/main.py", line 8, in <module>
    from utility.CustomLog import LOG
  File "/root/discordstuff/Genshin-Discord-Bot/utility/CustomLog.py", line 463, in <module>
    LOG = LogTool()
  File "/root/discordstuff/Genshin-Discord-Bot/utility/CustomLog.py", line 211, in __init__
    print(f"\n              {self._MIKU_GREEN}\u539f\u795e\u5c0f\u5e6b\u624b{self.RESET}              System : {self._LIGHT_CYAN}{platform.system()}\n"
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 33-37: ordinal not in range(256)
root@kvm5074:~/discordstuff/Genshin-Discord-Bot# 

this si what happeend when i try to run the main.py file

**Comment by GauravM512** [comment]
can u try commenting that print statement

**Comment by fakesmile0** [comment]
> 



> can u try commenting that print statement

If i try to comment out line 8 in main.py then it displays there is an error in line 9

**Comment by fakesmile0** [comment]
the erros contiue to transfer lines after lines

**Comment by fakesmile0** [comment]
Sorry  but now i commented out the prink statement 
Traceback (most recent call last):
  File "/root/discordstuff/Genshin-Discord-Bot/main.py", line 67, in <module>
    @client.tree.error
AttributeError: 'GenshinDiscordBot' object has no attribute 'tree'
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
now this error

**Comment by KT-Yeh** [comment]
try to use docker
