### ISSUE TITLE
請教 AttributeError: 'Database' object has no attribute 'db'

### ISSUE THREAD

**Issue by wibe01204** [KT-Yeh/Genshin-Discord-Bot#23]
剛剛轉移一下資料夾位置後，就出現以下報錯，還請指教 感謝

              原神小幫手              System : Windows
 Python v3.11.0   discord.py v2.1.0   genshin.py v1.4.0   LogTool v3.1

2022-12-07 15:29:02 WARNING  discord.ext.commands.bot Privileged message content intent is missing, commands may not work as expected.
Privileged message content intent is missing, commands may not work as expected.
2022-12-07 15:29:02 INFO     discord.client logging in using static token
logging in using static token
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\discord\client.py", line 817, in runner
    await self.start(token, reconnect=reconnect)
  File "C:\Python311\Lib\site-packages\discord\client.py", line 745, in start
    await self.login(token)
  File "C:\Python311\Lib\site-packages\discord\client.py", line 589, in login
    await self.setup_hook()
  File "D:\bot\Genshin-Discord-Bot-master\main.py", line 26, in setup_hook
    await self.load_extension('jishaku')
  File "C:\Python311\Lib\site-packages\discord\ext\commands\bot.py", line 1010, in load_extension
    raise errors.ExtensionNotFound(name)
discord.ext.commands.errors.ExtensionNotFound: Extension 'jishaku' could not be loaded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\bot\Genshin-Discord-Bot-master\main.py", line 72, in <module>
    client.run(config.bot_token)
  File "C:\Python311\Lib\site-packages\discord\client.py", line 828, in run
    asyncio.run(runner())
  File "C:\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\discord\client.py", line 816, in runner
    async with self:
  File "C:\Python311\Lib\site-packages\discord\client.py", line 276, in __aexit__
    await self.close()
  File "D:\bot\Genshin-Discord-Bot-master\main.py", line 53, in close
    await database.db.close()
  File "D:\bot\Genshin-Discord-Bot-master\data\database\database.py", line 51, in close
    await self.db.close()
          ^^^^^^^
AttributeError: 'Database' object has no attribute 'db'
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x00000175E5711400>, 2775.921)]']
connector: <aiohttp.connector.TCPConnector object at 0x00000175E5656690>

**Comment by KT-Yeh** [comment]
看起來是 jishaku 套件的問題，一種是用 python 3.10，另一種是將 jishaku 降成 2.5.0 版

**Comment by wibe01204** [comment]
> 看起是jishaku套件的問題，一種是用python 3.10，另一種是將jishaku降成2.5.0版

了解 我試試

**Comment by wibe01204** [comment]
@KT-Yeh 排除了 我忘記我有更新3.11了 感謝
