### ISSUE TITLE
自動檢查樹脂報錯

### ISSUE THREAD

**Issue by wibe01204** [KT-Yeh/Genshin-Discord-Bot#24]
抱歉我又來了 現在正常運行了，不過出現這些問題 還請指教><

[12-07 16:20:07]【系統】自動檢查樹脂開始
Task exception was never retrieved
future: <Task finished name='Task-88' coro=<Schedule.autoCheckResin() done, defined at D:\bot\Genshin-Discord-Bot-master\cogs\schedule.py:410> exception=IndexError('No item with that key')>
Traceback (most recent call last):
  File "D:\bot\Genshin-Discord-Bot-master\cogs\schedule.py", line 412, in autoCheckResin
    resin_users = await db.schedule_resin.getAll()
  File "D:\bot\Genshin-Discord-Bot-master\data\database\schedule_resin.py", line 154, in getAll
    return [ScheduleResin.fromRow(row) for row in rows]
  File "D:\bot\Genshin-Discord-Bot-master\data\database\schedule_resin.py", line 154, in <listcomp>
    return [ScheduleResin.fromRow(row) for row in rows]
  File "D:\bot\Genshin-Discord-Bot-master\data\database\schedule_resin.py", line 74, in fromRow
    if row["check_commission_time"]
IndexError: No item with that key

**Comment by KT-Yeh** [comment]
因為 ccacb96 加入檢查每日委託的功能，所以資料庫要新增一個欄位，在機器人的私訊輸入底下訊息

`$jsk py
await _bot.db.db.execute('ALTER TABLE schedule_resin ADD check_commission_time text')`

**Comment by wibe01204** [comment]
> 因為 [ccacb96](https://github.com/KT-Yeh/Genshin-Discord-Bot/commit/ccacb96405db144581227185219a9b031a18c827) 加入檢查每日委託的功能，所以資料庫要新增一個欄位，在機器人的私訊輸入底下訊息
> 
> `$jsk py await _bot.db.db.execute('ALTER TABLE schedule_resin ADD check_commission_time text')`

好的 感謝~
