### ISSUE TITLE
更新後報錯

### ISSUE THREAD

**Issue by wibe01204** [KT-Yeh/Genshin-Discord-Bot#29]
原神小幫手              System : Windows
 Python v3.9.13   discord.py v2.1.0   genshin.py v1.5.0   LogTool v3.1

2023-01-26 23:57:48 WARNING  discord.ext.commands.bot Privileged message content intent is missing, commands may not work as expected.
Privileged message content intent is missing, commands may not work as expected.
2023-01-26 23:57:48 INFO     discord.client logging in using static token
logging in using static token
[01-26 23:57:50]【系統】on_close: 資料庫已關閉
[01-26 23:57:50]【系統】on_close: 機器人已結束
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\discord\ext\commands\bot.py", line 934, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Bot\Genshin-Discord-Bot-master\cogs\admin.py", line 13, in <module>
    from yuanshen import automation
  File "D:\Bot\Genshin-Discord-Bot-master\yuanshen\automation.py", line 14, in <module>
    from . import errors, genshin_app, parser
  File "D:\Bot\Genshin-Discord-Bot-master\yuanshen\genshin_app.py", line 275, in <module>
    async def get_game_notices() -> Sequence[genshin.models.Announcement]:
AttributeError: module 'genshin.models' has no attribute 'Announcement'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Bot\Genshin-Discord-Bot-master\main.py", line 80, in <module>
    client.run(config.bot_token)
  File "C:\Python39\lib\site-packages\discord\client.py", line 828, in run
    asyncio.run(runner())
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Python39\lib\site-packages\discord\client.py", line 817, in runner
    await self.start(token, reconnect=reconnect)
  File "C:\Python39\lib\site-packages\discord\client.py", line 745, in start
    await self.login(token)
  File "C:\Python39\lib\site-packages\discord\client.py", line 589, in login
    await self.setup_hook()
  File "D:\Bot\Genshin-Discord-Bot-master\main.py", line 41, in setup_hook
    await self.load_extension(f"cogs.{cog_name}")
  File "C:\Python39\lib\site-packages\discord\ext\commands\bot.py", line 1012, in load_extension
    await self._load_from_module_spec(spec, name)
  File "C:\Python39\lib\site-packages\discord\ext\commands\bot.py", line 937, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.admin' raised an error: AttributeError: module 'genshin.models' has no attribute 'Announcement'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F9D84D49D0>
Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python39\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F9D84D49D0>
Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python39\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by GauravM512** [comment]
Update genshin.py 
```pip install --force-reinstall git+https://github.com/thesadru/genshin.py```

**Comment by wibe01204** [comment]
> Update genshin.py `pip install --force-reinstall git+https://github.com/thesadru/genshin.py`

一樣報錯 same wrong

原神小幫手              System : Windows
 Python v3.9.13   discord.py v2.1.0   genshin.py v1.5.0   LogTool v3.1

2023-01-27 08:58:38 WARNING  discord.ext.commands.bot Privileged message content intent is missing, commands may not work as expected.
Privileged message content intent is missing, commands may not work as expected.
2023-01-27 08:58:38 INFO     discord.client logging in using static token
logging in using static token
[01-27 08:58:40]【系統】on_close: 資料庫已關閉
[01-27 08:58:40]【系統】on_close: 機器人已結束
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\discord\ext\commands\bot.py", line 934, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Bot\Genshin-Discord-Bot-master\cogs\admin.py", line 13, in <module>
    from yuanshen import automation
  File "D:\Bot\Genshin-Discord-Bot-master\yuanshen\automation.py", line 14, in <module>
    from . import errors, genshin_app, parser
  File "D:\Bot\Genshin-Discord-Bot-master\yuanshen\genshin_app.py", line 275, in <module>
    async def get_game_notices() -> Sequence[genshin.models.Announcement]:
AttributeError: module 'genshin.models' has no attribute 'Announcement'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Bot\Genshin-Discord-Bot-master\main.py", line 80, in <module>
    client.run(config.bot_token)
  File "C:\Python39\lib\site-packages\discord\client.py", line 828, in run
    asyncio.run(runner())
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Python39\lib\site-packages\discord\client.py", line 817, in runner
    await self.start(token, reconnect=reconnect)
  File "C:\Python39\lib\site-packages\discord\client.py", line 745, in start
    await self.login(token)
  File "C:\Python39\lib\site-packages\discord\client.py", line 589, in login
    await self.setup_hook()
  File "D:\Bot\Genshin-Discord-Bot-master\main.py", line 41, in setup_hook
    await self.load_extension(f"cogs.{cog_name}")
  File "C:\Python39\lib\site-packages\discord\ext\commands\bot.py", line 1012, in load_extension
    await self._load_from_module_spec(spec, name)
  File "C:\Python39\lib\site-packages\discord\ext\commands\bot.py", line 937, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.admin' raised an error: AttributeError: module 'genshin.models' has no attribute 'Announcement'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000216A92149D0>
Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python39\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000216A92149D0>
Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python39\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by KT-Yeh** [comment]
改裝 python 3.10，然後用 pipenv 套件安裝虛擬環境來執行，詳細看 https://github.com/KT-Yeh/Genshin-Discord-Bot#方法2-python--套件安裝

**Comment by KT-Yeh** [comment]
你有照著我說的使用 pipenv 嗎?

**Comment by wibe01204** [comment]
> 你有照著我說的使用 pipenv 嗎?

有的~ 我全部重裝還是這樣

**Comment by KT-Yeh** [comment]
呃...可是我看你的錯誤訊息似乎沒有在虛擬環境下執行阿 
```
pipenv install
pipenv run python .\main.py
```

**Comment by wibe01204** [comment]
@KT-Yeh 
我知道為什麼了
我剛剛一直沒裝成功 xwx，現在可以了
感謝支援~
