### ISSUE TITLE
舊版架成功，架v2.0後新舊都不能用了

### ISSUE THREAD

**Issue by 27153216** [KT-Yeh/Genshin-Discord-Bot#3]
V2.0錯誤：
Traceback (most recent call last):
  File "main.py", line 37, in <module>
    client.run(config.bot_token)
  File "C:\Anaconda\envs\genshinbot\lib\site-packages\discord\client.py", line 712, in run
    asyncio.run(runner())
  File "C:\Anaconda\envs\genshinbot\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Anaconda\envs\genshinbot\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Anaconda\envs\genshinbot\lib\site-packages\discord\client.py", line 709, in runner
    await self.start(*args, **kwargs)
  File "C:\Anaconda\envs\genshinbot\lib\site-packages\discord\client.py", line 682, in start
    await self.login(token)
  File "C:\Anaconda\envs\genshinbot\lib\site-packages\discord\client.py", line 545, in login
    await self.setup_hook()
  File "main.py", line 25, in setup_hook
    await self.tree.sync(guild=test_guild)
  File "C:\Anaconda\envs\genshinbot\lib\site-packages\discord\app_commands\tree.py", line 925, in sync
    data = await self._http.bulk_upsert_guild_commands(self.client.application_id, guild.id, payload=payload)
  File "C:\Anaconda\envs\genshinbot\lib\site-packages\discord\http.py", line 495, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001D0F4AE39D0>
Traceback (most recent call last):
  File "C:\Anaconda\envs\genshinbot\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Anaconda\envs\genshinbot\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Anaconda\envs\genshinbot\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Anaconda\envs\genshinbot\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

v1.0錯誤
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    default_cooldown = commands.Cooldown(1, config.bot_cooldown, commands.BucketType.user)
TypeError: __init__() takes 3 positional arguments but 4 were given

**Comment by KT-Yeh** [comment]
第一個你檢查一下application_id、test_server_id有沒有設錯，然後你 bot 如果是從之前版本升級要重新用新連結邀請到伺服器，因為需要 applications commands 的權限

第二個你無法用 dicord.py v2.0 去執行舊版機器人，要降回 v1.7.3 才行，因為 discord.py 裡面的 API 版本不一樣

**Comment by 27153216** [comment]
v1版我重新架起來了
原因是我更新過discord v2.0，導致pip安裝時，即使我有輸入discord==1.7.3，似乎還是會自己抓到部分discord v2.0的cache，從而一直出錯，而在後方加上--no-cache-dir後就可以正常執行
問題是機器人雖然跑起來了，卻不會返回任何訊息了，cmd這邊有看到getRealtimeNote、getSpiralAbyss等訊息，但Discord頻道那邊依然只顯示"讀取中..."
後來發現原來是genshin套件的版本也不同，因為我的requirements.txt的版本是舊的，後來抓了指定版本後就恢復正常了

v2版則依舊，該設定的我都有設定正確了，虛擬環境也重弄了好幾個，包含使用--no-cache-dir來安裝套件，但錯誤訊息還是一樣，不清楚原因

**Comment by 27153216** [comment]
有開，我甚至整個app都砍掉踢掉重建重邀，還是一樣
![螢幕擷取畫面 2022-04-22 201936](https://user-images.githubusercontent.com/49145757/164713306-1af13a2c-9e93-4c09-8557-ff6578c66605.png)

**Comment by KT-Yeh** [comment]
那這個我就不太清楚了，我跟你的差別可能是 python 我是從官網裝的，你看起來是 Anaconda

目前我 windows 上 python 3.9、Linux 上 python 3.8，都可以正常運行，程式碼跟安裝方式都是跟 github 上一樣

**Comment by 27153216** [comment]
對，我的是 Anaconda 版本。
不過也還好，至少舊版能運行，等之後 discord.py v2.0 變成正式版再看看好了
感謝！
