### ISSUE TITLE
請教 cannot import name 'generate_image' from 'enka_network.enka_card'

### ISSUE THREAD

**Issue by wibe01204** [KT-Yeh/Genshin-Discord-Bot#31]
原神小幫手              System : Windows
 Python v3.10.9   discord.py v2.2.2   genshin.py v1.5.1   LogTool v3.1

PyNaCl is not installed, voice will NOT be supported
2023-03-10 23:58:53 WARNING  discord.ext.commands.bot Privileged message content intent is missing, commands may not work as expected.
Privileged message content intent is missing, commands may not work as expected.
2023-03-10 23:58:53 INFO     discord.client logging in using static token
logging in using static token
[03-10 23:58:55]【系統】on_close: 資料庫已關閉
[03-10 23:58:55]【系統】on_close: 機器人已結束
Traceback (most recent call last):
  File "C:\Users\wibe0\.virtualenvs\Genshin-Discord-Bot-fbdA0Dsy\lib\site-packages\discord\ext\commands\bot.py", line 935, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Bot\Genshin-Discord-Bot\cogs\genshin_showcase.py", line 11, in <module>
    from enka_network import Showcase, enka_assets
  File "D:\Bot\Genshin-Discord-Bot\enka_network\__init__.py", line 2, in <module>
    from .enka_card import generate_image
ImportError: cannot import name 'generate_image' from 'enka_network.enka_card' (unknown location)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Bot\Genshin-Discord-Bot\main.py", line 86, in <module>
    client.run(config.bot_token)
  File "C:\Users\wibe0\.virtualenvs\Genshin-Discord-Bot-fbdA0Dsy\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\wibe0\.virtualenvs\Genshin-Discord-Bot-fbdA0Dsy\lib\site-packages\discord\client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "C:\Users\wibe0\.virtualenvs\Genshin-Discord-Bot-fbdA0Dsy\lib\site-packages\discord\client.py", line 777, in start
    await self.login(token)
  File "C:\Users\wibe0\.virtualenvs\Genshin-Discord-Bot-fbdA0Dsy\lib\site-packages\discord\client.py", line 621, in login
    await self.setup_hook()
  File "D:\Bot\Genshin-Discord-Bot\main.py", line 42, in setup_hook
    await self.load_extension(f"cogs.{cog_name}")
  File "C:\Users\wibe0\.virtualenvs\Genshin-Discord-Bot-fbdA0Dsy\lib\site-packages\discord\ext\commands\bot.py", line 1013, in load_extension
    await self._load_from_module_spec(spec, name)
  File "C:\Users\wibe0\.virtualenvs\Genshin-Discord-Bot-fbdA0Dsy\lib\site-packages\discord\ext\commands\bot.py", line 938, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.genshin_showcase' raised an error: ImportError: cannot import name 'generate_image' from 'enka_network.enka_card' (unknown location)

**Comment by KT-Yeh** [comment]
Hi~
因為前幾天加入了 Git Submodule
而 github 預設的下載並沒有包含 Submodule 內的程式碼，
目前已將程式自動打包上傳到 Release 頁面
請到該頁面下載然後再試一次
 https://github.com/KT-Yeh/Genshin-Discord-Bot/releases

**Comment by wibe01204** [comment]
> Hi~ 因為前幾天加入了 Git Submodule 而 github 預設的下載並沒有包含 Submodule 內的程式碼， 目前已將程式自動打包上傳到 Release 頁面 請到該頁面下載然後再試一次 https://github.com/KT-Yeh/Genshin-Discord-Bot/releases

可以了~感謝!!!
