### ISSUE TITLE
更新1.2.0後報錯

### ISSUE THREAD

**Issue by wibe01204** [KT-Yeh/Genshin-Discord-Bot#38]
```
Traceback (most recent call last):
  File "D:\Bot\Genshin-Discord-Bot\main.py", line 9, in <module>
    from data import database
ImportError: cannot import name 'database' from 'data' (C:\Python311\Lib\site-packages\data\__init__.py) 
```

還請指教~

**Comment by KT-Yeh** [comment]
你的套件目錄有個 data 的名字跟機器人的資料夾重複了，建議用 pipenv 或 docker

**Comment by wibe01204** [comment]
```
PS D:\Bot\Genshin-Discord-Bot> pipenv run py .\main.py
Traceback (most recent call last):
  File "D:\Bot\Genshin-Discord-Bot\main.py", line 9, in <module>
    from data import database
  File "D:\Bot\Genshin-Discord-Bot\data\database\__init__.py", line 1, in <module>
    from .database import db
  File "D:\Bot\Genshin-Discord-Bot\data\database\database.py", line 5, in <module>
    from utility.custom_log import LOG
  File "D:\Bot\Genshin-Discord-Bot\utility\__init__.py", line 1, in <module>
    from .config import config
  File "D:\Bot\Genshin-Discord-Bot\utility\config.py", line 66, in <module>
    config = Config.parse_file(Path("config.json"), encoding="utf8")
  File "pydantic\main.py", line 570, in pydantic.main.BaseModel.parse_file
  File "pydantic\main.py", line 527, in pydantic.main.BaseModel.parse_obj
  File "pydantic\main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Config
notification_channel_id
  none is not an allowed value (type=type_error.none.not_allowed)
```
這樣呢~?

**Comment by GauravM512** [comment]
> ```
> PS D:\Bot\Genshin-Discord-Bot> pipenv run py .\main.py
> Traceback (most recent call last):
>   File "D:\Bot\Genshin-Discord-Bot\main.py", line 9, in <module>
>     from data import database
>   File "D:\Bot\Genshin-Discord-Bot\data\database\__init__.py", line 1, in <module>
>     from .database import db
>   File "D:\Bot\Genshin-Discord-Bot\data\database\database.py", line 5, in <module>
>     from utility.custom_log import LOG
>   File "D:\Bot\Genshin-Discord-Bot\utility\__init__.py", line 1, in <module>
>     from .config import config
>   File "D:\Bot\Genshin-Discord-Bot\utility\config.py", line 66, in <module>
>     config = Config.parse_file(Path("config.json"), encoding="utf8")
>   File "pydantic\main.py", line 570, in pydantic.main.BaseModel.parse_file
>   File "pydantic\main.py", line 527, in pydantic.main.BaseModel.parse_obj
>   File "pydantic\main.py", line 342, in pydantic.main.BaseModel.__init__
> pydantic.error_wrappers.ValidationError: 1 validation error for Config
> notification_channel_id
>   none is not an allowed value (type=type_error.none.not_allowed)
> ```
> 
> How about this~?

you have to add a notification channel to the config

**Comment by KT-Yeh** [comment]
add `"notification_channel_id": [],` in config.json

**Comment by wibe01204** [comment]
oh 抱歉沒看清楚更新註記~
已解決 感謝! Thanks!
