### ISSUE TITLE
docker部署报错

### ISSUE THREAD

**Issue by MuXia-0326** [KT-Yeh/Genshin-Discord-Bot#39]
错误日志如下，请作者大大解答
```bash
PyNaCl is not installed, voice will NOT be supported
2023-05-31 14:32:03 WARNING  discord.ext.commands.bot Privileged message content intent is missing, commands may not work as expected.
Privileged message content intent is missing, commands may not work as expected.
2023-05-31 14:32:03 INFO     discord.client logging in using static token
logging in using static token

              原神小幫手              System : Linux
 Python v3.10.11   discord.py v2.2.3   genshin.py v1.5.2   LogTool v3.1

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('69.63.178.13', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 777, in start
    await self.login(token)
  File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 612, in login
    data = await self.http.static_login(token)
  File "/usr/local/lib/python3.10/site-packages/discord/http.py", line 801, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/usr/local/lib/python3.10/site-packages/discord/http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [Connect call failed ('69.63.178.13', 443)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/main.py", line 87, in <module>
    client.run(config.bot_token)
  File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 848, in runner
    async with self:
  File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 308, in __aexit__
    await self.close()
  File "/app/main.py", line 62, in close
    await database.db.close()
  File "/app/data/database/database.py", line 59, in close
    await self.db.close()
AttributeError: 'Database' object has no attribute 'db'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd247c090f0>

```

**Comment by KT-Yeh** [comment]
你這看起來像連不到 discord 伺服器捏，檢查你的網路

**Comment by MuXia-0326** [comment]
> 你這看起來像連不到 discord 伺服器捏，檢查你的網路

原来如此，那请问一下有配置项可以指定代理吗？人在国内没办法直连discord的服务器

**Comment by KT-Yeh** [comment]
應該能從 docker 本身網路去設定吧，這樣整個容器連出去就會透過 proxy，可以參考看看官網說明

https://docs.docker.com/network/proxy/

**Comment by MuXia-0326** [comment]
> 應該能從 docker 本身網路去設定吧，這樣整個容器連出去就會透過 proxy，可以參考看看官網說明
> 
> https://docs.docker.com/network/proxy/

好的，我试试
