### ISSUE TITLE
No module named 'mihomo' Error

### ISSUE THREAD

**Issue by Murat1Na** [KT-Yeh/Genshin-Discord-Bot#41]
I get this error 

Traceback (most recent call last):
  File "/home/container/main.py", line 9, in <module>
    from data import database
  File "/home/container/data/database/__init__.py", line 1, in <module>
    from .database import db
  File "/home/container/data/database/database.py", line 11, in <module>
    from .starrail_showcase import StarrailShowcaseTable
  File "/home/container/data/database/starrail_showcase.py", line 5, in <module>
    from mihomo import StarrailInfoParsed
ModuleNotFoundError: No module named 'mihomo'

**Comment by Murat1Ahmet** [comment]
I tried with pip3 install mihomo, i got this error 

Traceback (most recent call last):
  File "/home/container/main.py", line 9, in <module>
    from data import database
  File "/home/container/data/database/__init__.py", line 1, in <module>
    from .database import db
  File "/home/container/data/database/database.py", line 11, in <module>
    from .starrail_showcase import StarrailShowcaseTable
  File "/home/container/data/database/starrail_showcase.py", line 5, in <module>
    from mihomo import StarrailInfoParsed
ImportError: cannot import name 'StarrailInfoParsed' from 'mihomo' (/home/container/.local/lib/python3.10/site-packages/mihomo/__init__.py)

**Comment by KT-Yeh** [comment]
use `pipenv install`

**Comment by Murat1Ahmet** [comment]
bash: pipenv: command not found

**Comment by Shutoparu** [comment]
```pip install -U git+https://github.com/KT-Yeh/mihomo.git``` should work
