### ISSUE TITLE
Unknown interaction

### ISSUE THREAD

**Issue by MikeWuang** [KT-Yeh/Genshin-Discord-Bot#43]
點開深淵查詢之後得到以下錯誤

2023-07-27 09:14:45 GenshinDiscordBot        | [07-27 09:14:45]【指令】@astsrrytwinkle(346665960377417731) 使用了 /abyss深淵紀錄：season=PREVIOUS_SEASON, user=@賽庭春(853565242592460840)
2023-07-27 09:14:46 GenshinDiscordBot        | [07-27 09:14:46]【指令】⤷ @astsrrytwinkle(346665960377417731) 使用 /abyss深淵紀錄 成功。耗時： 1228 毫秒(ms)
2023-07-27 09:14:52 GenshinDiscordBot        | 2023-07-27 09:14:52 ERROR    discord.ui.view Ignoring exception in view <View timeout=120.0 children=1> for item <AbyssFloorDropdown placeholder='選擇樓層：' min_values=1 max_values=1 disabled=False options=[<SelectOption label='📁 儲存本次紀錄' value='SAVE' description='保存此次紀錄到資料庫，之後可從歷史紀錄查看' emoji=None default=False>, <SelectOption label='[★9] 第 9 層' value='0' description='雷電將軍.八重神子.旅行者.納西妲 ／\n夜蘭.珊瑚宮心海.申鶴.神里綾華' emoji=None default=False>, <SelectOption label='[★9] 第 10 層' value='1' description='雷電將軍.八重神子.納西妲.旅行者 ／\n夜蘭.珊瑚宮心海.申鶴.甘雨' emoji=None default=False>, <SelectOption label='[★9] 第 11 層' value='2' description='夜蘭.珊瑚宮心海.申鶴.神里綾華 ／\n雷電將軍.八重神子.琴.納西妲' emoji=None default=False>, <SelectOption label='[★9] 第 12 層' value='3' description='雷電將軍.八重神子.珊瑚宮心海.納西妲 ／\n夜蘭.班尼特.香菱.神里綾華' emoji=None default=False>]>
2023-07-27 09:14:52 GenshinDiscordBot        | Traceback (most recent call last):
2023-07-27 09:14:52 GenshinDiscordBot        |   File "/usr/local/lib/python3.10/site-packages/discord/ui/view.py", line 427, in _scheduled_task
2023-07-27 09:14:52 GenshinDiscordBot        |     await item.callback(interaction)
2023-07-27 09:14:52 GenshinDiscordBot        |   File "/app/./cogs/abyss/ui.py", line 116, in callback
2023-07-27 09:14:52 GenshinDiscordBot        |     await interaction.response.edit_message(
2023-07-27 09:14:52 GenshinDiscordBot        |   File "/usr/local/lib/python3.10/site-packages/discord/interactions.py", line 921, in edit_message
2023-07-27 09:14:52 GenshinDiscordBot        |     await adapter.create_interaction_response(
2023-07-27 09:14:52 GenshinDiscordBot        |   File "/usr/local/lib/python3.10/site-packages/discord/webhook/async_.py", line 219, in request
2023-07-27 09:14:52 GenshinDiscordBot        |     raise NotFound(response, data)
2023-07-27 09:14:52 GenshinDiscordBot        | discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
2023-07-27 09:14:52 GenshinDiscordBot        | Ignoring exception in view <View timeout=120.0 children=1> for item <AbyssFloorDropdown placeholder='選擇樓層：' min_values=1 max_values=1 disabled=False options=[<SelectOption label='📁 儲存本次紀錄' value='SAVE' description='保存此次紀錄到資料庫，之後可從歷史紀錄查看' emoji=None default=False>, <SelectOption label='[★9] 第 9 層' value='0' description='雷電將軍.八重神子.旅行者.納西妲 ／\n夜蘭.珊瑚宮心海.申鶴.神里綾華' emoji=None default=False>, <SelectOption label='[★9] 第 10 層' value='1' description='雷電將軍.八重神子.納西妲.旅行者 ／\n夜蘭.珊瑚宮心海.申鶴.甘雨' emoji=None default=False>, <SelectOption label='[★9] 第 11 層' value='2' description='夜蘭.珊瑚宮心海.申鶴.神里綾華 ／\n雷電將軍.八重神子.琴.納西妲' emoji=None default=False>, <SelectOption label='[★9] 第 12 層' value='3' description='雷電將軍.八重神子.珊瑚宮心海.納西妲 ／\n夜蘭.班尼特.香菱.神里綾華' emoji=None default=False>]>
2023-07-27 09:14:52 GenshinDiscordBot        | Traceback (most recent call last):
2023-07-27 09:14:52 GenshinDiscordBot        |   File "/usr/local/lib/python3.10/site-packages/discord/ui/view.py", line 427, in _scheduled_task
2023-07-27 09:14:52 GenshinDiscordBot        |     await item.callback(interaction)
2023-07-27 09:14:52 GenshinDiscordBot        |   File "/app/./cogs/abyss/ui.py", line 116, in callback
2023-07-27 09:14:52 GenshinDiscordBot        |     await interaction.response.edit_message(
2023-07-27 09:14:52 GenshinDiscordBot        |   File "/usr/local/lib/python3.10/site-packages/discord/interactions.py", line 921, in edit_message
2023-07-27 09:14:52 GenshinDiscordBot        |     await adapter.create_interaction_response(
2023-07-27 09:14:52 GenshinDiscordBot        |   File "/usr/local/lib/python3.10/site-packages/discord/webhook/async_.py", line 219, in request
2023-07-27 09:14:52 GenshinDiscordBot        |     raise NotFound(response, data)
2023-07-27 09:14:52 GenshinDiscordBot        | discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

**Comment by KT-Yeh** [comment]
第一次會下載角色圖片，你電腦下載速度慢會使指令超過 3 秒以上才回覆，Discord Server 判定回覆失敗。所以這是正常現象，第二次使用之後就不會了

**Comment by MikeWuang** [comment]
![image](https://github.com/KT-Yeh/Genshin-Discord-Bot/assets/33493455/efe0040a-24e4-4e48-be3e-b335fb2abe9d)
沒有，一直這樣 我也不知道怎麼辦 爬文有爬到改程式的部分但是我能力不足 目前還是沒辦法使用這個功能

**Comment by KT-Yeh** [comment]
不知道你架設在哪裡，不過這錯誤代碼 (error code: 10062) 表示機器人沒在 3 秒內做出反應，這反應時間包含了 (1) 機器人請求 Hoyolab 的時間、(2) 機器人與 Discord 伺服器 (地點在美東) 的延遲、(2) 上傳圖片的速度

**Comment by MikeWuang** [comment]
我朋友當初想要拿自己電腦架不過因為要開Hyper-V 所以我幫它弄成了VM跑在電腦上
目前用的是 Win10 22H2 在 VMWare 17 上
圖形驗證和其他的功能都是正常的 唯獨只有深淵的功能會有問題
![image](https://github.com/KT-Yeh/Genshin-Discord-Bot/assets/33493455/4a9a4694-7502-4556-ba06-51ba8683942d)
https://www.youtube.com/watch?v=9LuBpdkUm54

**Comment by KT-Yeh** [comment]
我更新了一版

你把 docker-compose.yml 檔案第五行改成底下

```
image: ghcr.io/kt-yeh/genshin-discord-bot:develop
```

重新 `docker compose pull` 然後再運行試試

**Comment by MikeWuang** [comment]
他現在變成機率性的失敗 有時成功有時失敗
https://www.youtube.com/watch?v=r0GzePc_Yno

我跟朋友都有換過IMAGE了 不過他那邊仍失敗 有什麼我可以提供的資料嗎

**Comment by KT-Yeh** [comment]
你現在 pull 一次 image 再試看看

**Comment by MikeWuang** [comment]
沒問題了 
![image](https://github.com/KT-Yeh/Genshin-Discord-Bot/assets/33493455/7933d67e-ec60-4158-b92f-ab97d830c98f)
我剛剛pull完後測試沒問題 我朋友說有問題
結果是他pull之前每有把container 刪掉 現在都好了 感謝:😇
