### ISSUE TITLE
No module named :  Alembic

### ISSUE THREAD

**Issue by WQ9CT** [KT-Yeh/Genshin-Discord-Bot#44]
File "/home/container/main.py", line 11, in <module>
    import database
  File "/home/container/database/__init__.py", line 1, in <module>
    from .app import Database
  File "/home/container/database/app.py", line 5, in <module>
    from alembic import command as alembic_cmd
ModuleNotFoundError: No module named 'alembic'

请问我该怎么解决？

**Comment by KT-Yeh** [comment]
`pipenv install`

**Comment by WQ9CT** [comment]
谢谢，关于alembic的问题我已经成功解决，但是在启动时又出现另一项问题：

[09-18 13:55:24]【系統】on_close: 資料庫已關閉
[09-18 13:55:24]【系統】on_close: 機器人已結束
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 284, in _do_get
    return self._create_connection()
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 615, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 317, in connect
    await_only(connection),
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 125, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 185, in greenlet_spawn
    value = await result
  File "/home/container/.local/lib/python3.10/site-packages/aiosqlite/core.py", line 141, in _connect
    self._connection = await future
  File "/home/container/.local/lib/python3.10/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
  File "/home/container/.local/lib/python3.10/site-packages/aiosqlite/core.py", line 401, in connector
    return sqlite3.connect(loc, **kwargs)
sqlite3.OperationalError: unable to open database file
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/container/main.py", line 97, in <module>
    client.run(config.bot_token)
  File "/home/container/.local/lib/python3.10/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/container/.local/lib/python3.10/site-packages/discord/client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "/home/container/.local/lib/python3.10/site-packages/discord/client.py", line 777, in start
    await self.login(token)
  File "/home/container/.local/lib/python3.10/site-packages/discord/client.py", line 621, in login
    await self.setup_hook()
  File "/home/container/main.py", line 32, in setup_hook
    await database.Database.init()
  File "/home/container/database/app.py", line 44, in init
    async with cls.engine.begin() as conn:
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/engine.py", line 1059, in begin
    async with conn:
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/base.py", line 127, in __aenter__
    return await self.start(is_ctxmanager=True)  # type: ignore
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/engine.py", line 268, in start
    await greenlet_spawn(self.sync_engine.connect)
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3264, in connect
    return self._connection_cls(self)
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2426, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 284, in _do_get
    return self._create_connection()
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 615, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 317, in connect
    await_only(connection),
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 125, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 185, in greenlet_spawn
    value = await result
  File "/home/container/.local/lib/python3.10/site-packages/aiosqlite/core.py", line 141, in _connect
    self._connection = await future
  File "/home/container/.local/lib/python3.10/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
  File "/home/container/.local/lib/python3.10/site-packages/aiosqlite/core.py", line 401, in connector
    return sqlite3.connect(loc, **kwargs)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)__

请问该怎么解决？

**Comment by KT-Yeh** [comment]
`sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file`

sqlite 無法開檔，跟你本地環境有關係，無法幫你解決

**Comment by Lucifer7535** [comment]
检查你是否安装了sqlite3。

如果未安装，则安装它。

**Comment by Lucifer7535** [comment]
> 谢谢，关于alembic的问题我已经成功解决，但是在启动时又出现另一项问题：
> 
> [09-18 13:55:24]【系統】on_close: 資料庫已關閉 [09-18 13:55:24]【系統】on_close: 機器人已結束 Traceback (most recent call last): File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in **init** self._dbapi_connection = engine.raw_connection() File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection return self.pool.connect() File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 452, in connect return _ConnectionFairy._checkout(self) File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1267, in _checkout fairy = _ConnectionRecord.checkout(pool) File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 716, in checkout rec = pool._do_get() File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 284, in _do_get return self._create_connection() File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection return _ConnectionRecord(self) File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 678, in **init** self.__connect() File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 902, in __connect with util.safe_reraise(): File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in **exit** raise exc_value.with_traceback(exc_tb) File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 898, in __connect self.dbapi_connection = connection = pool._invoke_creator(self) File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 637, in connect return dialect.connect(*cargs, **cparams) File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 615, in connect return self.loaded_dbapi.connect(*cargs, **cparams) File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 317, in connect await_only(connection), File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 125, in await_only return current.driver.switch(awaitable) # type: ignore[no-any-return] File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 185, in greenlet_spawn value = await result File "/home/container/.local/lib/python3.10/site-packages/aiosqlite/core.py", line 141, in _connect self._connection = await future File "/home/container/.local/lib/python3.10/site-packages/aiosqlite/core.py", line 106, in run result = function() File "/home/container/.local/lib/python3.10/site-packages/aiosqlite/core.py", line 401, in connector return sqlite3.connect(loc, **kwargs) sqlite3.OperationalError: unable to open database file The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/home/container/main.py", line 97, in client.run(config.bot_token) File "/home/container/.local/lib/python3.10/site-packages/discord/client.py", line 860, in run asyncio.run(runner()) File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete return future.result() File "/home/container/.local/lib/python3.10/site-packages/discord/client.py", line 849, in runner await self.start(token, reconnect=reconnect) File "/home/container/.local/lib/python3.10/site-packages/discord/client.py", line 777, in start await self.login(token) File "/home/container/.local/lib/python3.10/site-packages/discord/client.py", line 621, in login await self.setup_hook() File "/home/container/main.py", line 32, in setup_hook await database.Database.init() File "/home/container/database/app.py", line 44, in init async with cls.engine.begin() as conn: File "/usr/local/lib/python3.10/contextlib.py", line 199, in **aenter** return await anext(self.gen) File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/engine.py", line 1059, in begin async with conn: File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/base.py", line 127, in **aenter** return await self.start(is_ctxmanager=True) # type: ignore File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/engine.py", line 268, in start await greenlet_spawn(self.sync_engine.connect) File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn result = context.throw(*sys.exc_info()) File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3264, in connect return self._connection_cls(self) File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 147, in **init** Connection._handle_dbapi_exception_noconnection( File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2426, in _handle_dbapi_exception_noconnection raise sqlalchemy_exception.with_traceback(exc_info[2]) from e File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in **init** self._dbapi_connection = engine.raw_connection() File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection return self.pool.connect() File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 452, in connect return _ConnectionFairy._checkout(self) File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1267, in _checkout fairy = _ConnectionRecord.checkout(pool) File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 716, in checkout rec = pool._do_get() File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 284, in _do_get return self._create_connection() File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection return _ConnectionRecord(self) File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 678, in **init** self.__connect() File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 902, in __connect with util.safe_reraise(): File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in **exit** raise exc_value.with_traceback(exc_tb) File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 898, in __connect self.dbapi_connection = connection = pool._invoke_creator(self) File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 637, in connect return dialect.connect(*cargs, **cparams) File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 615, in connect return self.loaded_dbapi.connect(*cargs, **cparams) File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 317, in connect await_only(connection), File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 125, in await_only return current.driver.switch(awaitable) # type: ignore[no-any-return] File "/home/container/.local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 185, in greenlet_spawn value = await result File "/home/container/.local/lib/python3.10/site-packages/aiosqlite/core.py", line 141, in _connect self._connection = await future File "/home/container/.local/lib/python3.10/site-packages/aiosqlite/core.py", line 106, in run result = function() File "/home/container/.local/lib/python3.10/site-packages/aiosqlite/core.py", line 401, in connector return sqlite3.connect(loc, **kwargs) sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file (Background on this error at: https://sqlalche.me/e/20/e3q8)__
> 
> 请问该怎么解决？

检查你是否安装了sqlite3。

如果未安装，则安装它。

**Comment by Lucifer7535** [comment]
> `sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file`
> 
> sqlite 無法開檔，跟你本地環境有關係，無法幫你解決

你能提供bot.db的结构吗？

我也遇到了同样的错误，所以我安装了 sqlite3 并在文件夹 /data/bot/bot.db 中创建了一个名为 bot.db 的数据库，没有任何表

后来我收到此错误没有名为表
starrail_schedule_notes。

所以我认为要修复这个错误，我需要有 bot.db 文件的结构。

希望翻译是正确的。
