### ISSUE TITLE
docker 部署問題

### ISSUE THREAD

**Issue by DyingSilver** [KT-Yeh/Genshin-Discord-Bot#79]
以下是 docker 裡的 terminal ，請作者大大幫忙解答
```
HoyolabGeetestWebserver  | INFO:     Started server process [1]
HoyolabGeetestWebserver  | INFO:     Waiting for application startup.
HoyolabGeetestWebserver  | INFO:     Application startup complete.
HoyolabGeetestWebserver  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
GenshinDiscordBot        | PyNaCl is not installed, voice will NOT be supported
GenshinDiscordBot        | 2024-09-15 06:32:24 WARNING  discord.ext.commands.bot Privileged message content intent is missing, commands may not work as expected.
GenshinDiscordBot        | Privileged message content intent is missing, commands may not work as expected.
GenshinDiscordBot        | 2024-09-15 06:32:24 INFO     discord.client logging in using static token
GenshinDiscordBot        | logging in using static token
GenshinDiscordBot        | Context impl SQLiteImpl.
GenshinDiscordBot        | Will assume non-transactional DDL.
GenshinDiscordBot        | [09-15 06:32:25]【系統】on_close: 資料庫已關閉
GenshinDiscordBot        | [09-15 06:32:25]【系統】on_close: 機器人已結束
GenshinDiscordBot        | 
GenshinDiscordBot        |               原神小幫手              System : Linux
GenshinDiscordBot        |  Python v3.10.12   discord.py v2.4.0   genshin.py v1.7.1   LogTool v3.1
GenshinDiscordBot        | 
GenshinDiscordBot        | Traceback (most recent call last):
GenshinDiscordBot        |   File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1203, in _create_direct_connection
GenshinDiscordBot        |     hosts = await self._resolve_host(host, port, traces=traces)
GenshinDiscordBot        |   File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 880, in _resolve_host
GenshinDiscordBot        |     return await asyncio.shield(resolved_host_task)
GenshinDiscordBot        |   File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 917, in _resolve_host_with_throttle
GenshinDiscordBot        |     addrs = await self._resolver.resolve(host, port, family=self._family)
GenshinDiscordBot        |   File "/usr/local/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
GenshinDiscordBot        |     infos = await self._loop.getaddrinfo(
GenshinDiscordBot        |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
GenshinDiscordBot        |     return await self.run_in_executor(
GenshinDiscordBot        |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
GenshinDiscordBot        |     result = self.fn(*self.args, **self.kwargs)
GenshinDiscordBot        |   File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
GenshinDiscordBot        |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
GenshinDiscordBot        | socket.gaierror: [Errno -2] Name or service not known
GenshinDiscordBot        | 
GenshinDiscordBot        | The above exception was the direct cause of the following exception:
GenshinDiscordBot        | 
GenshinDiscordBot        | Traceback (most recent call last):
GenshinDiscordBot        |   File "/app/main.py", line 102, in <module>
GenshinDiscordBot        |     client.run(config.bot_token)
GenshinDiscordBot        |   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 869, in run
GenshinDiscordBot        |     asyncio.run(runner())
GenshinDiscordBot        |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
GenshinDiscordBot        |     return loop.run_until_complete(main)
GenshinDiscordBot        |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
GenshinDiscordBot        |     return future.result()
GenshinDiscordBot        |   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 858, in runner
GenshinDiscordBot        |     await self.start(token, reconnect=reconnect)
GenshinDiscordBot        |   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 786, in start
GenshinDiscordBot        |     await self.login(token)
GenshinDiscordBot        |   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 629, in login
GenshinDiscordBot        |     await self.setup_hook()
GenshinDiscordBot        |   File "/app/main.py", line 39, in setup_hook
GenshinDiscordBot        |     await genshin.utility.update_characters_ambr(["zh-tw"])
GenshinDiscordBot        |   File "/usr/local/lib/python3.10/site-packages/genshin/utility/extdb.py", line 195, in update_characters_ambr
GenshinDiscordBot        |     characters_list = await _fetch_jsons(*urls)
GenshinDiscordBot        |   File "/usr/local/lib/python3.10/site-packages/genshin/utility/extdb.py", line 109, in _fetch_jsons
GenshinDiscordBot        |     return await asyncio.gather(*(_fetch_and_parse(url) for url in urls))
GenshinDiscordBot        |   File "/usr/local/lib/python3.10/site-packages/genshin/utility/extdb.py", line 106, in _fetch_and_parse
GenshinDiscordBot        |     r = await session.get(url)
GenshinDiscordBot        |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 581, in _request
GenshinDiscordBot        |     conn = await self._connector.connect(
GenshinDiscordBot        |   File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 544, in connect
GenshinDiscordBot        |     proto = await self._create_connection(req, traces, timeout)
GenshinDiscordBot        |   File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 944, in _create_connection
GenshinDiscordBot        |     _, proto = await self._create_direct_connection(req, traces, timeout)
GenshinDiscordBot        |   File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
GenshinDiscordBot        |     raise ClientConnectorError(req.connection_key, exc) from exc
GenshinDiscordBot        | aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.ambr.top:443 ssl:default [Name or service not known]
```

**Comment by KT-Yeh** [comment]
v2.6.1 已修正
